export function buildApiRoutes({ authRoutes = [], handlers }) {
  return [
    ...authRoutes,
    { method: "GET", pattern: /^\/health$/, handler: handlers.handleHealth },
    { method: "GET", pattern: /^\/integrations\/meta\/webhook\/status$/, handler: handlers.handleMetaWebhookStatus },
    { method: "GET", pattern: /^\/integrations\/meta\/webhook$/, handler: handlers.handleMetaWebhookVerify },
    { method: "POST", pattern: /^\/integrations\/meta\/webhook$/, handler: handlers.handleMetaWebhookIngest },
    { method: "GET", pattern: /^\/staging-access\/login$/, handler: handlers.handleStagingAccessLoginPage },
    { method: "POST", pattern: /^\/staging-access\/login$/, handler: handlers.handleStagingAccessLoginSubmit },
    { method: "GET", pattern: /^\/staging-access\/check$/, handler: handlers.handleStagingAccessCheck },
    { method: "GET", pattern: /^\/staging-access\/logout$/, handler: handlers.handleStagingAccessLogout },
    { method: "GET", pattern: /^\/public\/v1\/mobile\/bootstrap$/, handler: handlers.handleMobileBootstrap },
    { method: "GET", pattern: /^\/public\/v1\/tours$/, handler: handlers.handlePublicListTours },
    { method: "GET", pattern: /^\/public\/v1\/tour-images\/(.+)$/, handler: handlers.handlePublicTourImage },
    { method: "GET", pattern: /^\/public\/v1\/customer-photos\/(.+)$/, handler: handlers.handlePublicCustomerPhoto },
    { method: "GET", pattern: /^\/public\/v1\/customer-consent-evidence\/(.+)$/, handler: handlers.handlePublicConsentEvidence },
    { method: "POST", pattern: /^\/public\/v1\/bookings$/, handler: handlers.handleCreateBooking },
    { method: "GET", pattern: /^\/api\/v1\/bookings$/, handler: handlers.handleListBookings },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)$/, handler: handlers.handleGetBooking },
    { method: "DELETE", pattern: /^\/api\/v1\/bookings\/([^/]+)$/, handler: handlers.handleDeleteBooking },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/chat$/, handler: handlers.handleListBookingChatEvents },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/stage$/, handler: handlers.handlePatchBookingStage },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/client$/, handler: handlers.handlePatchBookingClient },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/client\/create-customer$/, handler: handlers.handleCreateBookingCustomer },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/client\/members$/, handler: handlers.handleCreateBookingGroupMember },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/owner$/, handler: handlers.handlePatchBookingOwner },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/notes$/, handler: handlers.handlePatchBookingNotes },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/pricing$/, handler: handlers.handlePatchBookingPricing },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/offer$/, handler: handlers.handlePatchBookingOffer },
    { method: "POST", pattern: /^\/api\/v1\/offers\/exchange-rates$/, handler: handlers.handlePostOfferExchangeRates },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/activities$/, handler: handlers.handleListActivities },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/activities$/, handler: handlers.handleCreateActivity },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices$/, handler: handlers.handleListBookingInvoices },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices$/, handler: handlers.handleCreateBookingInvoice },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices\/([^/]+)$/, handler: handlers.handlePatchBookingInvoice },
    { method: "GET", pattern: /^\/api\/v1\/invoices\/([^/]+)\/pdf$/, handler: handlers.handleGetInvoicePdf },
    { method: "GET", pattern: /^\/api\/v1\/customers$/, handler: handlers.handleListCustomers },
    { method: "GET", pattern: /^\/api\/v1\/customers\/([^/]+)$/, handler: handlers.handleGetCustomer },
    { method: "PATCH", pattern: /^\/api\/v1\/customers\/([^/]+)$/, handler: handlers.handlePatchCustomer },
    { method: "DELETE", pattern: /^\/api\/v1\/customers\/([^/]+)$/, handler: handlers.handleDeleteCustomer },
    { method: "POST", pattern: /^\/api\/v1\/customers\/([^/]+)\/photo$/, handler: handlers.handleUploadCustomerPhoto },
    { method: "POST", pattern: /^\/api\/v1\/customers\/([^/]+)\/consents$/, handler: handlers.handleCreateCustomerConsent },
    { method: "GET", pattern: /^\/api\/v1\/travel_groups$/, handler: handlers.handleListTravelGroups },
    { method: "POST", pattern: /^\/api\/v1\/travel_groups$/, handler: handlers.handleCreateTravelGroup },
    { method: "GET", pattern: /^\/api\/v1\/travel_groups\/([^/]+)$/, handler: handlers.handleGetTravelGroup },
    { method: "PATCH", pattern: /^\/api\/v1\/travel_groups\/([^/]+)$/, handler: handlers.handlePatchTravelGroup },
    { method: "DELETE", pattern: /^\/api\/v1\/travel_groups\/([^/]+)$/, handler: handlers.handleDeleteTravelGroup },
    { method: "DELETE", pattern: /^\/api\/v1\/travel_groups\/([^/]+)\/members\/([^/]+)$/, handler: handlers.handleDeleteTravelGroupMember },
    { method: "GET", pattern: /^\/api\/v1\/atp_staff$/, handler: handlers.handleListAtpStaff },
    { method: "POST", pattern: /^\/api\/v1\/atp_staff$/, handler: handlers.handleCreateAtpStaff },
    { method: "GET", pattern: /^\/api\/v1\/tours$/, handler: handlers.handleListTours },
    { method: "GET", pattern: /^\/api\/v1\/tours\/([^/]+)$/, handler: handlers.handleGetTour },
    { method: "POST", pattern: /^\/api\/v1\/tours$/, handler: handlers.handleCreateTour },
    { method: "PATCH", pattern: /^\/api\/v1\/tours\/([^/]+)$/, handler: handlers.handlePatchTour },
    { method: "POST", pattern: /^\/api\/v1\/tours\/([^/]+)\/image$/, handler: handlers.handleUploadTourImage },
  ];
}
