export function buildApiRoutes({ authRoutes = [], handlers }) {
  return [
    ...authRoutes,
    { method: "GET", pattern: /^\/health$/, handler: handlers.handleHealth },
    { method: "GET", pattern: /^\/integrations\/meta\/webhook\/status$/, handler: handlers.handleMetaWebhookStatus },
    { method: "GET", pattern: /^\/integrations\/meta\/webhook$/, handler: handlers.handleMetaWebhookVerify },
    { method: "POST", pattern: /^\/integrations\/meta\/webhook$/, handler: handlers.handleMetaWebhookIngest },
    { method: "GET", pattern: /^\/staging-access\/login$/, handler: handlers.handleStagingAccessLoginPage },
    { method: "POST", pattern: /^\/staging-access\/login$/, handler: handlers.handleStagingAccessLoginSubmit },
    { method: "GET", pattern: /^\/staging-access\/check$/, handler: handlers.handleStagingAccessCheck },
    { method: "GET", pattern: /^\/staging-access\/logout$/, handler: handlers.handleStagingAccessLogout },
    { method: "GET", pattern: /^\/public\/v1\/mobile\/bootstrap$/, handler: handlers.handleMobileBootstrap },
    { method: "GET", pattern: /^\/public\/v1\/tours$/, handler: handlers.handlePublicListTours },
    { method: "GET", pattern: /^\/public\/v1\/tour-images\/(.+)$/, handler: handlers.handlePublicTourImage },
    { method: "GET", pattern: /^\/public\/v1\/booking-images\/(.+)$/, handler: handlers.handlePublicBookingImage },
    { method: "GET", pattern: /^\/public\/v1\/booking-person-photos\/(.+)$/, handler: handlers.handlePublicBookingPersonPhoto },
    { method: "POST", pattern: /^\/public\/v1\/bookings$/, handler: handlers.handleCreateBooking },
    { method: "GET", pattern: /^\/api\/v1\/bookings$/, handler: handlers.handleListBookings },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)$/, handler: handlers.handleGetBooking },
    { method: "DELETE", pattern: /^\/api\/v1\/bookings\/([^/]+)$/, handler: handlers.handleDeleteBooking },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/chat$/, handler: handlers.handleListBookingChatEvents },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/name$/, handler: handlers.handlePatchBookingName },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/image$/, handler: handlers.handleUploadBookingImage },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/stage$/, handler: handlers.handlePatchBookingStage },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/owner$/, handler: handlers.handlePatchBookingOwner },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/persons$/, handler: handlers.handleCreateBookingPerson },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/persons\/([^/]+)$/, handler: handlers.handlePatchBookingPerson },
    { method: "DELETE", pattern: /^\/api\/v1\/bookings\/([^/]+)\/persons\/([^/]+)$/, handler: handlers.handleDeleteBookingPerson },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/persons\/([^/]+)\/photo$/, handler: handlers.handleUploadBookingPersonPhoto },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/notes$/, handler: handlers.handlePatchBookingNotes },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/pricing$/, handler: handlers.handlePatchBookingPricing },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/offer$/, handler: handlers.handlePatchBookingOffer },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/generated-offers$/, handler: handlers.handleGenerateBookingOffer },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/generated-offers\/([^/]+)\/pdf$/, handler: handlers.handleGetGeneratedOfferPdf },
    { method: "POST", pattern: /^\/api\/v1\/offers\/exchange-rates$/, handler: handlers.handlePostOfferExchangeRates },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/activities$/, handler: handlers.handleListActivities },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/activities$/, handler: handlers.handleCreateActivity },
    { method: "GET", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices$/, handler: handlers.handleListBookingInvoices },
    { method: "POST", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices$/, handler: handlers.handleCreateBookingInvoice },
    { method: "PATCH", pattern: /^\/api\/v1\/bookings\/([^/]+)\/invoices\/([^/]+)$/, handler: handlers.handlePatchBookingInvoice },
    { method: "GET", pattern: /^\/api\/v1\/invoices\/([^/]+)\/pdf$/, handler: handlers.handleGetInvoicePdf },
    { method: "GET", pattern: /^\/api\/v1\/keycloak_users$/, handler: handlers.handleListKeycloakUsers },
    { method: "GET", pattern: /^\/api\/v1\/tours$/, handler: handlers.handleListTours },
    { method: "GET", pattern: /^\/api\/v1\/tours\/([^/]+)$/, handler: handlers.handleGetTour },
    { method: "POST", pattern: /^\/api\/v1\/tours$/, handler: handlers.handleCreateTour },
    { method: "PATCH", pattern: /^\/api\/v1\/tours\/([^/]+)$/, handler: handlers.handlePatchTour },
    { method: "POST", pattern: /^\/api\/v1\/tours\/([^/]+)\/image$/, handler: handlers.handleUploadTourImage },
  ];
}
