package enums

#BookingStage: "NEW" | "QUALIFIED" | "PROPOSAL_SENT" | "NEGOTIATION" | "INVOICE_SENT" | "PAYMENT_RECEIVED" | "WON" | "LOST" | "POST_TRIP"

BookingStageCatalog: [
	"NEW",
	"QUALIFIED",
	"PROPOSAL_SENT",
	"NEGOTIATION",
	"INVOICE_SENT",
	"PAYMENT_RECEIVED",
	"WON",
	"LOST",
	"POST_TRIP",
]
