package enums

BookingActivityTypeCatalog: [
	"BOOKING_CREATED",
	"STAGE_CHANGED",
	"BOOKING_LIFECYCLE_UPDATED",
	"BOOKING_MILESTONE_UPDATED",
	"ASSIGNMENT_CHANGED",
	"NOTE_UPDATED",
	"TRAVEL_PLAN_UPDATED",
	"PRICING_UPDATED",
	"OFFER_UPDATED",
	"OFFER_TRANSLATED",
	"OFFER_EMAIL_DRAFT_CREATED",
	"OFFER_ACCEPTANCE_OTP_SENT",
	"OFFER_ACCEPTED",
	"INVOICE_CREATED",
	"INVOICE_UPDATED",
	"PAYMENT_UPDATED",
]

#BookingActivityType: or(BookingActivityTypeCatalog)
