package enums

#OfferCategory: "ACCOMMODATION" | "TRANSPORTATION" | "TOURS_ACTIVITIES" | "GUIDE_SUPPORT_SERVICES" | "MEALS" | "FEES_TAXES" | "DISCOUNTS_CREDITS" | "OTHER"

OfferCategoryCatalog: [
	"ACCOMMODATION",
	"TRANSPORTATION",
	"TOURS_ACTIVITIES",
	"GUIDE_SUPPORT_SERVICES",
	"MEALS",
	"FEES_TAXES",
	"DISCOUNTS_CREDITS",
	"OTHER",
]
